### ISSUE TITLE
動作の高速化

### ISSUE THREAD

**Issue by KojiAndoJC** [polm/posuto#18]
類似ライブラリの jusho と動作速度がかなり違うようです。

```py
import timeit
import posuto

timeit.timeit(lambda: posuto.get('160-0021'), number=100)
```
→7.848345300000801

```py
import timeit
from jusho import Jusho

postman = Jusho()

timeit.timeit(lambda: postman.by_zip_code('160-0021'), number=100)
```
→0.018534900002123322

どちらも同じような実装に見えたので不思議に思いソースコードを眺めたのですが、jusho では以下のように SQLite のテーブルにインデックスが作成されている一方で、posuto のほうでは該当する処理が見当たらなかったため、これが原因かもしれません。（勘違いでしたらすみません。）
https://github.com/nagataaaas/Jusho/blob/5fa5037d42c16e1dceca693afd9a04f269815f90/jusho/gateway/insert.py#L37

jusho は大口事業所個別番号などには対応していないようで、posuto を使いたい場面も出てくるかもしれませんので、もし何かしら高速化が可能でしたらご検討いただけると助かります。

**Comment by polm** [comment]
ご報告ありがとうございます、高速化についてはあまり考えていませんでした。indexをかけてみます。

**Comment by polm** [comment]
こちらでindexをかけてみた結果、確かに簡単に高速化できたようです。

- index無し 2.7267031759984093
- indexあり 0.006765697995433584

ファイル容量に少し影響がありますが、特に問題なさそうです。index作成のコードを追加して、早速リリースしました。
