### ISSUE TITLE
Use data from https://github.com/geolonia/japanese-addresses

### ISSUE THREAD

**Issue by urijah** [polm/posuto#2]
I see a similar js library that has come out, that also incorporates data from https://nlftp.mlit.go.jp/cgi-bin/isj/dls/_choose_method.cgi

Have you thought about using their data in posuto?

**Comment by polm** [comment]
Thanks for the note. 

I am aware of the repo and while it does seem related to posuto, I don't know that there's a natural way to integrate it. Their data uses the neighborhood/大字町丁目 as the fundamental unit and doesn't include postal codes at all, while posuto is focused on postal codes. They do use the same postal code data posuto does, but only for kana/romaji. 

It might be possible to match posuto's neighborhood data to the coordinates, but I don't have any specific plans to do so at the moment.

**Comment by polm** [comment]
Looking at their issues, they have also said that integrating postal codes is difficult given the way postal codes and neighborhoods don't really line up. 

https://github.com/geolonia/japanese-addresses/issues/9

**Comment by urijah** [comment]
Oh, that's too bad...maybe there is a way to "translate" between the two using lat/long. Thank you for taking a look!
