### ISSUE TITLE
Library isn't thread safe

### ISSUE THREAD

**Issue by rtpg** [polm/posuto#7]
From me trying to use this inside a Django application:
```
  [...snip...]
  File "/home/rtpg/.virtualenvs/hats-env/lib/python3.8/site-packages/posuto/posuto.py", line 53, in get
    base = dict(_fetch_code(code))
  File "/home/rtpg/.virtualenvs/hats-env/lib/python3.8/site-packages/posuto/posuto.py", line 17, in _fetch_code
    DB.execute("select data from postal_data where code = ?", (code,))
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140451714606912 and this is thread id 140450079946496.
```

My understanding is that web servers like gunicorn run in a pre-fork model, where they import all your application, _then_ fork the process into worker threads. So, in particular, stuff like `import posuto` will run on a different thread

Since we're using a global cursor here, instead of a thread-local, we run into this conflict

https://github.com/polm/posuto/blob/fac2a63096f19363ba0a5f4dc6caf61b44df984a/posuto/posuto.py#L11

My guess is that just having some thread-local (you can have multiple read connections to sqlite without issue, to my knowledge) would let this code transparently work. My current workaround is to set up the import until after the fork.

**Comment by rtpg** [comment]
By the way, this is what I'm going with for now as a monkeypatch, I feel like there's probably a cleaner solution though

```
from posuto import posuto as posuto_internal

# The following is a thread-local patch for posuto
zipcode_connection = threading.local()

def _get_zipcode_db():
    """
    A thread-safe version of posuto.posuto.DB
    (there's probably a way to connection pool instead of one connection per thread)
    https://github.com/polm/posuto/blob/master/posuto/posuto.py#L11
    """
    if hasattr(zipcode_connection, 'DB'):
        return zipcode_connection.DB
    conn = sqlite3.connect(posuto_internal.DBPATH)
    zipcode_connection.DB = conn.cursor()
    return zipcode_connection.DB


def patched_fetch_code(code):
    """
    This is a patched-in lookup method for posuto, until the library itself becomes threadsafe

    https://github.com/polm/posuto/issues/7
    """
    pass
    DB = _get_zipcode_db()
    DB.execute("select data from postal_data where code = ?", (code,))
    res = DB.fetchone()
    if res:
        return json.loads(res[0])

    raise KeyError("No such postal code: " + code)

# confirm the method still exists before patching
assert posuto_internal._fetch_code
posuto_internal._fetch_code = patched_fetch_code

# this ends the thread-local patch for posuto
```

**Comment by polm** [comment]
Thanks for the report, I had not run posuto in that context. 

One thing I considered when switching to sqlite was storage was using an object to access the DB to avoid having an open connection around, so usage would be like this:

    import posuto
    post = posuto.Posuto()
    post.get(...)

I decided against it for interface consistency, but this is a case where it's obvious useful. I'll think about the best way to handle this for a bit.

**Comment by rtpg** [comment]
One option that would maintain interface consistency but you might need a bit of confidence is to disable the Same Thread check (when you do `sqlite3.connect`, you can pass in `check_same_thread=False`), and add a simple lock at query points. 

This is of course a solution of the "oh, it's just a little concurrency primitives, how bad could it be?" variety, but it would let you share a single connection. And if it's only reads anyways this should be totally safe, from my understanding (docs say you need to worry about writes but nothing said about reads)

**Comment by polm** [comment]
I created a connection manager class and added notes about it in the [README](https://github.com/polm/posuto#multi-threaded-environments). Basically you can do this now:

```
from posuto import Posuto

with Posuto() as pp:
    tower = pp.get('〒105-0011')
```

The old method of the single connection is still there, but you can use this wrapper if you need it in situations like yours. I'm going to go ahead and close this but let me know if you have any issues, and thanks for reporting.
